### ISSUE TITLE
Heatbooster ip has wrong type

### ISSUE THREAD

**Issue by PW999** [PW999/home-assistant-config#33]
```
Logger: homeassistant.components.mqtt.models
Source: components/sensor/__init__.py:583
Integration: MQTT (documentation, issues)
First occurred: May 7, 2023 at 2:32:33 PM (19911 occurrences)
Last logged: 9:50:53 PM

Exception raised when updating state of sensor.heatbooster_front_window_ip, topic: 'heatbooster-front-window/ip' with payload: b'192.168.0.163'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: '192.168.0.163'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.heatbooster_front_window_ip has device class None, state class None unit  and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 192.168.0.163 (<class 'str'>)

```

**Comment by PW999** [comment]
I tried this, but it doesn't work :( 

```yaml
homeassistant:
  customize:
    sensor.heatbooster_front_window_ip:
      device_class: enum
```

`ValueError: Sensor sensor.heatbooster_front_window_ip has device class None, state class None unit  and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 1.2.3.4 (<class 'str'>)`

🤷‍♂️

**Comment by PW999** [comment]
Updated heatbooster to firmware 2.1.12 (from 2.1.4 or something) and now it seems to work.
=> https://www.sdr-engineering.nl/webshop/index.php?route=product/product&product_id=50
